### ISSUE TITLE
Modify README.md

### ISSUE THREAD

**Issue by BALaka-18** [BALaka-18/rake_new2#1]
## Description
Add the mentioned link in the README file just above the 'Installation' heading. The link should be displayed as 'READ MORE ABOUT RAKE' and should point to the URL : https://monkeylearn.com/keyword-extraction/

## Acceptance Criteria
- [ ] README must be properly formatted.
- [ ] All instructions provided in the Description must be strictly followed.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Time Estimation
10 minutes.

**Comment by chookity-pokk** [comment]
Can I work on this?

**Comment by BALaka-18** [comment]
> Can I work on this?

Uh @ragreenburg the first two issues are reserved, I'll get them done as they are a bit urgent.
There are two more beginner-friendly issues for Hacktoberfest, check them out : )

**Comment by chookity-pokk** [comment]
Okay, I already did it though haha.

**Comment by BALaka-18** [comment]
> Okay, I already did it though haha.

Okay not a problem. But if you are participating in Hacktoberfest, then all pull requests generated after Oct 1 shall be counted.

**Comment by chookity-pokk** [comment]
Alright, not an issue. Just trying to figure out how to do this stuff.

**Comment by 16sweetyjain** [comment]
since this issue is open, can i still work on it?

**Comment by BALaka-18** [comment]
> since this issue is open, can i still work on it?

@16sweetyjain this issue is not open, I have assigned myself as it is a minor change. Right now issue #9 is open. You can claim it if you are comfortable doing it.
