### ISSUE TITLE
cleaning the repository and adding a .gitignore

### ISSUE THREAD

**Issue by etnnth** [BALaka-18/rake_new2#14]
For now run and build artifacts are inside the repository:
    - build
    - dist
    - \_\_pycache\_\_
    - egg-info
They should be remove from the repository.
In order to avoid future unwanted build and run artifacts to be committed in the repository we should add a .gitignore file.
I propose to take the python project gitignore from https://www.toptal.com/developers/gitignore. It's the classic .gitignore file for python project.

If you are ok with those changes I have a branch ready for a pull request!

**Comment by BALaka-18** [comment]
Sure, go ahead. Assigned to you.
