### ISSUE TITLE
Add Hacktoberfest logo to README.md

### ISSUE THREAD

**Issue by BALaka-18** [BALaka-18/rake_new2#2]
## Description
Add the Hacktoberfest logo to the very start of the README file and add the link to the Contributing_Guidelines.md file and the Issues tab in the repository. The links should read : 

1. 'CLICK HERE TO START CONTRIBUTING' --> Link to the Issues tab.

2. 'READ THE CONTRIBUTING GUIDELINES' --> Link to the Contributing_Guidelines.md file

## Acceptance Criteria
- [ ] README must be properly formatted.
- [ ] All instructions provided in the Description must be strictly followed.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Time Estimation
10 minutes.

**Comment by martinoywa** [comment]
Hi, is it okay if I work on this?

**Comment by BALaka-18** [comment]
> Hi, is it okay if I work on this?

Hi @martinoywa please consider issues from #3  onwards. The first two have been resolved by me.
#3 and #4  are also beginner level issues.

**Comment by martinoywa** [comment]
Ahh, okay thanks. I'll delete the new PR then.
