### ISSUE TITLE
Create a CONTRIBUTORS.md file

### ISSUE THREAD

**Issue by BALaka-18** [BALaka-18/rake_new2#3]
## Description
Create a CONTRIBUTORS.md file that must contain the name of the contributors whose PRs get merged.
Format : 

Contributor's GitHub profile picture as a thumbnail || Contributor Name(It must be a link to the contributor's GitHub profile) || Merged PR number.

## Acceptance Criteria
- [ ] CONTRIBUTORS.md file must be properly formatted.
- [ ] All instructions provided in the Description must be strictly followed.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Time Estimation
Recurring process

**Comment by geekusa33** [comment]
May I work on this?

**Comment by BALaka-18** [comment]
> May I work on this?

@askalik sure, you may start working on it. 
However, if you're participating in Hacktoberfest, make sure to **create your PR after 1st October, else it won't be considered.**

**Comment by mohinimahato** [comment]
@BALaka-18 hi there, I'll be participating on hacktober fest, can I work on this from October?

**Comment by BALaka-18** [comment]
> @BALaka-18 hi there, I'll be participating on hacktober fest, can I work on this from October?

Hey @Mohini0104, this issue has already been assigned to someone else. If he can't complete it or if he needs extra help, I'll assign it to you.

**Comment by mohinimahato** [comment]
@BALaka-18 Okay , Thank You.

**Comment by kanishkaa24** [comment]
@BALaka-18 
Is this issue open to work on for DWOC?
If yes, I would love to work on this.  Kindly assign this to me.

**Comment by BALaka-18** [comment]
> @BALaka-18
> Is this issue open to work on for DWOC?
> If yes, I would love to work on this. Kindly assign this to me.

@kanishkaa24, no this issue is not open for DWOC. Kindly look for other issues or open new ones if needed.
