### ISSUE TITLE
Create CODE_OF_CONDUCT

### ISSUE THREAD

**Issue by tharunc** [BALaka-18/rake_new2#38]

**Comment by akrish4** [comment]
Kindly assign me this issue 
@tharunc 
@BALaka-18

**Comment by BALaka-18** [comment]
@tharunc henceforth please provide a wholesome description for your Issue and wait till I assign it to you, before creating a PR.
Closing the previous PR, follow the steps correctly.

@akrish4 as this issue's been opened by someone else other than the maintainer, it automatically gets assigned to him/her if the Issue description is correct. If he/she can't deliver the PR on time, it'll be assigned to the next in line.
You can check out the other issues as well.

**Comment by tharunc** [comment]
Sorry for the inconvenience. Please assign me this issue, I will update the CODE_OF_CONDUCT without any discrepancy.

**Comment by akrish4** [comment]
ok sure @BALaka-18

**Comment by BALaka-18** [comment]
> Sorry for the inconvenience. Please assign me this issue, I will update the CODE_OF_CONDUCT without any discrepancy.

Write a proper Issue description.
And do read this **[comment](https://github.com/BALaka-18/rake_new2/pull/39#issuecomment-752327250)** before moving forward.

**Comment by akrish4** [comment]
@BALaka-18  let me know if i can open a new issue for the same with description.
since its been 2 days no update rregarding it.

**Comment by BALaka-18** [comment]
> @BALaka-18 let me know if I can open a new issue for the same with description.
> since it's been 2 days no update regarding it.

Yes, you may.

**Comment by BALaka-18** [comment]
@tharunc  Closing this issue due to lack of improvement or further action from your side.
