### ISSUE TITLE
CODE OF CONDUCT 

### ISSUE THREAD

**Issue by akrish4** [BALaka-18/rake_new2#41]
We know code of conduct is a very important thing to be followed when many are contributing in a single project , 
Let me give a description about the code of conduct ,
- There will be a pledge which all need to follow so  that this  community  get a harassment-free experience for everyone, regardless of age, body size, disability, ethnicity etc while contributing and we take this pledge to follow the decorum  in conversation in issues also.
- There will be Standards like :
           -  Examples of unacceptable behavior by participants 
           - Examples of behavior that contributes to creating a positive environment
- Responsibilities 
- And if any one faces any issues from other contributors , how to contact ? 
- Scope of code of conduct like `This Code of Conduct applies both within project spaces and in public spaces`
These are the things i will be adding , in little more descriptive way 
let me know if you can assign me @BALaka-18

**Comment by BALaka-18** [comment]
Assigning.

**Comment by akrish4** [comment]
@BALaka-18    Kindly do check and merge it and also pls do add the same labels added in the issue to pr also  
#45

**Comment by BALaka-18** [comment]
@akrish4 Please read this **[comment](https://github.com/BALaka-18/rake_new2/pull/45#issuecomment-753583533)**

**Comment by akrish4** [comment]
@BALaka-18 I have to close this pr right ?
so that i can open a new pr to the dwoc-contribution branch

**Comment by akrish4** [comment]
Kindly do check and merge it 
#47

**Comment by akrish4** [comment]
issue resolved 
#47
