### ISSUE TITLE
Add Contributors.md file

### ISSUE THREAD

**Issue by muthuannamalai12** [BALaka-18/rake_new2#42]
Hai,
I would love to add the Contributors.md file to your project in the form of a table and display a link to it in the README.md file

**Comment by muthuannamalai12** [comment]
I would love to work on this issue as a part of DWOC. Kindly assign it to me.

**Comment by BALaka-18** [comment]
Contributors' list will be added manually to the README by the maintainer at the end of DWOC. Kindly raise other issues. 
Thank you for exploring rake_new2.

**Comment by muthuannamalai12** [comment]
> Contributors' list will be added manually to the README by the maintainer at the end of DWOC. Kindly raise other issues. 
> Thank you for exploring rake_new2.

Ok. Thank you
