### ISSUE TITLE
Create Issue Template

### ISSUE THREAD

**Issue by muthuannamalai12** [BALaka-18/rake_new2#51]
Hai,
I would love to add an issue template for your repository. This template would have four issues namely bug, documentation, feature, proposal and question

**Comment by muthuannamalai12** [comment]
I would love to work on this issue as a part of DWOC. Kindly assign it to me

**Comment by BALaka-18** [comment]
Not required. Any incoming issue must have a proper, well-written description for it to be approved.
Closing this.
