### ISSUE TITLE
Integrate welcome bot

### ISSUE THREAD

**Issue by muthuannamalai12** [BALaka-18/rake_new2#52]
I can add a welcome bot config file having a proper message that will show up when any user will open up an issue or pull-request for the first time.
For reference, check out: https://github.com/apps/welcome

Please assign it to me.

**Comment by muthuannamalai12** [comment]
I would love to work on this issue as a part of DWOC.Kindly assign it to me

**Comment by BALaka-18** [comment]
We already have a welcome bot. Please go through the whole repository meticulously before raising an issue.
Closing this.
